/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Id".
 */
export type Id = string;
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Revision".
 */
export type Revision = number;
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Utc".
 */
export type Utc = string;

export interface LILAProtocolV1DesignContracts {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Error".
 */
export interface Error {
  code: string;
  message: string;
  retryable: boolean;
  correlation_id: string;
  current_revision?: Revision;
  blocking_reasons?: string[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Criteria".
 */
export interface Criteria {
  /**
   * @maxItems 20
   */
  titles:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * @maxItems 20
   */
  locations:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * @maxItems 50
   */
  conditions: {
    field:
      | "work_mode"
      | "experience"
      | "employment_type"
      | "posting_age_days"
      | "company_include"
      | "company_exclude"
      | "salary";
    mode: "MUST" | "PREFERENCE";
    /**
     * @minItems 1
     * @maxItems 50
     */
    values: [string, ...string[]];
  }[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "CreateTask".
 */
export interface CreateTask {
  command_id: string;
  account_id: string;
  instruction: string;
  criteria: Criteria;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "TaskCommand".
 */
export interface TaskCommand {
  command_id: string;
  expected_revision: Revision;
  operation: "start" | "pause" | "resume" | "stop" | "restart";
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "GlobalCommand".
 */
export interface GlobalCommand {
  command_id: string;
  expected_revision: Revision;
  operation: "pause_all" | "resume_all" | "quit";
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "ApprovalCommand".
 */
export interface ApprovalCommand {
  command_id: string;
  expected_revision: Revision;
  operation: "approve" | "reject";
  payload_version: string;
  /**
   * @minItems 1
   * @maxItems 100
   */
  members: [
    {
      action_id: string;
      payload_version: string;
    },
    ...{
      action_id: string;
      payload_version: string;
    }[]
  ];
  expires_at?: Utc;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "FactCommand".
 */
export interface FactCommand {
  command_id: string;
  expected_revision?: Revision;
  operation: "propose" | "verify" | "mark_stale" | "reject";
  field_key: string;
  value: string | number | boolean;
  source_version?: string;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Policy".
 */
export interface Policy {
  command_id: string;
  account_id: string;
  /**
   * @minItems 1
   */
  action_kinds: [
    "submit_application" | "discover_jobs" | "prepare_application",
    ...("submit_application" | "discover_jobs" | "prepare_application")[]
  ];
  /**
   * @minItems 1
   */
  domains: ["www.linkedin.com", ..."www.linkedin.com"[]];
  /**
   * @minItems 1
   */
  tab_scope: [number, ...number[]];
  expires_at: Utc;
  run_cap: number;
  daily_cap: number;
  timezone: string;
  budget_micro_usd: number;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "ManualOutcome".
 */
export interface ManualOutcome {
  command_id: string;
  expected_revision: Revision;
  operation: "continue_manually" | "mark_submitted" | "mark_not_submitted" | "leave_unresolved";
  note?: string;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Receipt".
 */
export interface Receipt {
  command_id: string;
  accepted: boolean;
  entity_id: string;
  revision: Revision;
  state: string;
  blocking_reasons: string[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "TaskSnapshot".
 */
export interface TaskSnapshot {
  task_id: string;
  run_id: string | null;
  revision: Revision;
  state: "DRAFT" | "QUEUED" | "ACTIVE" | "AWAITING_INPUT" | "BLOCKED" | "PAUSED" | "STOPPED" | "COMPLETED";
  individual_hold: boolean;
  global_hold: boolean;
  blocking_reasons: string[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  cursor: number;
  event_id: string;
  occurred_at: Utc;
  entity_type: string;
  entity_id: string;
  revision: Revision;
  kind: string;
  summary: {
    state?: string;
    message?: string;
  };
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "LeaseAcquire".
 */
export interface LeaseAcquire {
  command_id: string;
  worker_id: string;
  generation: number;
  wait_seconds: number;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "Heartbeat".
 */
export interface Heartbeat {
  worker_id: string;
  generation: number;
  lease_id: string;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "DraftOutput".
 */
export interface DraftOutput {
  /**
   * @maxItems 100
   */
  answers: {
    field_key: string;
    answer: string;
    /**
     * @maxItems 100
     */
    fact_version_ids: string[];
    needs_input: boolean;
    reason: string;
  }[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "ActionProposal".
 */
export interface ActionProposal {
  command_id: string;
  lease_id: string;
  generation: number;
  run_id: string;
  logical_step_key: string;
  application_id: string;
  payload_version: string;
  draft_id: string;
  kind: "submit_application" | "fill_fields" | "advance_step" | "attach_document" | "discover_jobs";
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "BrowserAction".
 */
export interface BrowserAction {
  protocol_version: 1;
  action_id: string;
  run_id: string;
  generation: number;
  account_id: string;
  tab_id: number;
  allowed_origin: "https://www.linkedin.com";
  payload_version: string;
  expires_at: Utc;
  tool:
    | "inspect_context"
    | "discover_jobs"
    | "inspect_form"
    | "fill_fields"
    | "attach_document"
    | "advance_step"
    | "submit_application"
    | "inspect_outcome";
  adapter_id: string;
  form_fingerprint?: string;
  arguments: {
    /**
     * @maxItems 100
     */
    field_values?: {
      field_key: string;
      value: string;
    }[];
    document_capability?: string;
    expected_step?: string;
    query?: Criteria;
    existing_action_id?: string;
  };
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "BrowserOutcome".
 */
export interface BrowserOutcome {
  action_id: string;
  generation: number;
  outcome: "RECEIVED" | "CONFIRMED" | "FAILED" | "UNCERTAIN" | "UNSUPPORTED_VARIANT";
  not_submitted_proven: boolean;
  observed_at: Utc;
  job_id: string;
  form_fingerprint: string;
  /**
   * @maxItems 20
   */
  evidence:
    | []
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ]
    | [
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        },
        {
          kind: "STATUS_TEXT" | "VALIDATION_ERROR" | "APPLIED_STATE" | "SCREENSHOT_REF";
          value: string;
        }
      ];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "PrivacyCommand".
 */
export interface PrivacyCommand {
  command_id: string;
  operation:
    "export_preview" | "export_confirm" | "delete_preview" | "delete_confirm" | "restore_preview" | "restore_confirm";
  /**
   * @minItems 1
   * @maxItems 1000
   */
  subject_ids: [string, ...string[]];
  preview_id?: string;
  expected_revision?: Revision;
  encrypted?: boolean;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "CheckpointPut".
 */
export interface CheckpointPut {
  command_id: string;
  run_id: string;
  generation: number;
  namespace: string;
  checkpoint_id: string;
  parent_id: string | null;
  checkpoint_json: string;
  metadata_json: string;
  new_versions_json: string;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "CheckpointWrites".
 */
export interface CheckpointWrites {
  command_id: string;
  run_id: string;
  generation: number;
  namespace: string;
  checkpoint_id: string;
  task_id: string;
  task_path: string;
  /**
   * @maxItems 1000
   */
  writes: {
    index: number;
    channel: string;
    value_json: string;
  }[];
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "WorkAssignment".
 */
export interface WorkAssignment {
  available: boolean;
  lease: {
    lease_id: Id;
    run_id: Id;
    worker_id: Id;
    generation: number;
    expires_at: Utc;
    work_kind: "DISCOVER" | "PREPARE" | "RECONCILE";
  } | null;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "HeartbeatResult".
 */
export interface HeartbeatResult {
  lease_id: Id;
  generation: number;
  expires_at: Utc;
  fenced: boolean;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "CheckpointConfig".
 */
export interface CheckpointConfig {
  thread_id: Id;
  checkpoint_ns: string;
  checkpoint_id: string;
}
/**
 * This interface was referenced by `LILAProtocolV1DesignContracts`'s JSON-Schema
 * via the `definition` "CheckpointWriteResult".
 */
export interface CheckpointWriteResult {
  checkpoint_id: string;
  accepted_writes: number;
}
