# generated by datamodel-codegen:
#   filename:  protocol-v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class LilaProtocolV1DesignContracts(RootModel[Any]):
    root: Annotated[Any, Field(title='LILA protocol v1 design contracts')]


class Id(RootModel[UUID]):
    root: UUID


class Revision(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class Utc(RootModel[AwareDatetime]):
    root: AwareDatetime


class BlockingReason(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=64, min_length=1)]
    message: Annotated[str, Field(max_length=500, min_length=1)]
    retryable: bool
    correlation_id: UUID
    current_revision: Revision | None = None
    blocking_reasons: list[BlockingReason] | None = None


class Title(RootModel[str]):
    root: Annotated[str, Field(max_length=150, min_length=1)]


class Location(RootModel[str]):
    root: Annotated[str, Field(max_length=150, min_length=1)]


class FieldModel(Enum):
    work_mode = 'work_mode'
    experience = 'experience'
    employment_type = 'employment_type'
    posting_age_days = 'posting_age_days'
    company_include = 'company_include'
    company_exclude = 'company_exclude'
    salary = 'salary'


class Mode(Enum):
    MUST = 'MUST'
    PREFERENCE = 'PREFERENCE'


class Value(RootModel[str]):
    root: Annotated[str, Field(max_length=150, min_length=1)]


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: FieldModel
    mode: Mode
    values: Annotated[list[Value], Field(max_length=50, min_length=1)]


class Criteria(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    titles: Annotated[list[Title], Field(max_length=20)]
    locations: Annotated[list[Location], Field(max_length=20)]
    conditions: Annotated[list[Condition], Field(max_length=50)]


class CreateTask(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    account_id: UUID
    instruction: Annotated[str, Field(max_length=10000, min_length=1)]
    criteria: Criteria


class Operation(Enum):
    start = 'start'
    pause = 'pause'
    resume = 'resume'
    stop = 'stop'
    restart = 'restart'


class TaskCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    expected_revision: Revision
    operation: Operation


class Operation1(Enum):
    pause_all = 'pause_all'
    resume_all = 'resume_all'
    quit = 'quit'


class GlobalCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    expected_revision: Revision
    operation: Operation1


class Operation2(Enum):
    approve = 'approve'
    reject = 'reject'


class Member(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: UUID
    payload_version: UUID


class ApprovalCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    expected_revision: Revision
    operation: Operation2
    payload_version: UUID
    members: Annotated[list[Member], Field(max_length=100, min_length=1)]
    expires_at: Utc | None = None


class Operation3(Enum):
    propose = 'propose'
    verify = 'verify'
    mark_stale = 'mark_stale'
    reject = 'reject'


class Value1(RootModel[str]):
    root: Annotated[str, Field(max_length=10000, min_length=1)]


class FactCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    expected_revision: Revision | None = None
    operation: Operation3
    field_key: Annotated[str, Field(max_length=100, min_length=1)]
    value: Value1 | int | bool
    source_version: UUID | None = None


class ActionKind(Enum):
    submit_application = 'submit_application'
    discover_jobs = 'discover_jobs'
    prepare_application = 'prepare_application'


class Domain(Enum):
    www_linkedin_com = 'www.linkedin.com'


class TabScopeItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Policy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    account_id: UUID
    action_kinds: Annotated[list[ActionKind], Field(min_length=1)]
    domains: Annotated[list[Domain], Field(min_length=1)]
    tab_scope: Annotated[list[TabScopeItem], Field(min_length=1)]
    expires_at: Utc
    run_cap: Annotated[int, Field(ge=1)]
    daily_cap: Annotated[int, Field(ge=1)]
    timezone: Annotated[str, Field(max_length=100, min_length=1)]
    budget_micro_usd: Annotated[int, Field(ge=0)]


class Operation4(Enum):
    continue_manually = 'continue_manually'
    mark_submitted = 'mark_submitted'
    mark_not_submitted = 'mark_not_submitted'
    leave_unresolved = 'leave_unresolved'


class ManualOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    expected_revision: Revision
    operation: Operation4
    note: Annotated[str | None, Field(max_length=1000)] = None


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    accepted: bool
    entity_id: UUID
    revision: Revision
    state: Annotated[str, Field(max_length=40, min_length=1)]
    blocking_reasons: list[BlockingReason]


class State(Enum):
    DRAFT = 'DRAFT'
    QUEUED = 'QUEUED'
    ACTIVE = 'ACTIVE'
    AWAITING_INPUT = 'AWAITING_INPUT'
    BLOCKED = 'BLOCKED'
    PAUSED = 'PAUSED'
    STOPPED = 'STOPPED'
    COMPLETED = 'COMPLETED'


class TaskSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: UUID
    run_id: UUID | None
    revision: Revision
    state: State
    individual_hold: bool
    global_hold: bool
    blocking_reasons: list[BlockingReason]


class Summary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    state: Annotated[str | None, Field(max_length=40)] = None
    message: Annotated[str | None, Field(max_length=250)] = None


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cursor: Annotated[int, Field(ge=0)]
    event_id: UUID
    occurred_at: Utc
    entity_type: Annotated[str, Field(max_length=50, min_length=1)]
    entity_id: UUID
    revision: Revision
    kind: Annotated[str, Field(max_length=80, min_length=1)]
    summary: Summary


class LeaseAcquire(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    worker_id: UUID
    generation: Annotated[int, Field(ge=1)]
    wait_seconds: Annotated[int, Field(ge=0, le=20)]


class Heartbeat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    worker_id: UUID
    generation: Annotated[int, Field(ge=1)]
    lease_id: UUID


class Answer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_key: Annotated[str, Field(max_length=100, min_length=1)]
    answer: Annotated[str, Field(max_length=5000)]
    fact_version_ids: Annotated[list[UUID], Field(max_length=100)]
    needs_input: bool
    reason: Annotated[str, Field(max_length=300)]


class DraftOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    answers: Annotated[list[Answer], Field(max_length=100)]


class Kind(Enum):
    submit_application = 'submit_application'
    fill_fields = 'fill_fields'
    advance_step = 'advance_step'
    attach_document = 'attach_document'
    discover_jobs = 'discover_jobs'


class ActionProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    lease_id: UUID
    generation: Annotated[int, Field(ge=1)]
    run_id: UUID
    logical_step_key: Annotated[str, Field(max_length=200, min_length=1)]
    application_id: UUID
    payload_version: UUID
    draft_id: UUID
    kind: Kind


class Tool(Enum):
    inspect_context = 'inspect_context'
    discover_jobs = 'discover_jobs'
    inspect_form = 'inspect_form'
    fill_fields = 'fill_fields'
    attach_document = 'attach_document'
    advance_step = 'advance_step'
    submit_application = 'submit_application'
    inspect_outcome = 'inspect_outcome'


class FieldValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_key: Annotated[str, Field(max_length=100, min_length=1)]
    value: Annotated[str, Field(max_length=5000)]


class Arguments(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_values: Annotated[list[FieldValue] | None, Field(max_length=100)] = None
    document_capability: Annotated[str | None, Field(max_length=500, min_length=1)] = (
        None
    )
    expected_step: Annotated[str | None, Field(max_length=100, min_length=1)] = None
    query: Criteria | None = None
    existing_action_id: UUID | None = None


class BrowserAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal[1]
    action_id: UUID
    run_id: UUID
    generation: Annotated[int, Field(ge=1)]
    account_id: UUID
    tab_id: Annotated[int, Field(ge=0)]
    allowed_origin: Literal['https://www.linkedin.com']
    payload_version: UUID
    expires_at: Utc
    tool: Tool
    adapter_id: Annotated[str, Field(max_length=100, min_length=1)]
    form_fingerprint: Annotated[str | None, Field(pattern='^[a-f0-9]{64}$')] = None
    arguments: Arguments


class Outcome(Enum):
    RECEIVED = 'RECEIVED'
    CONFIRMED = 'CONFIRMED'
    FAILED = 'FAILED'
    UNCERTAIN = 'UNCERTAIN'
    UNSUPPORTED_VARIANT = 'UNSUPPORTED_VARIANT'


class Kind1(Enum):
    STATUS_TEXT = 'STATUS_TEXT'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    APPLIED_STATE = 'APPLIED_STATE'
    SCREENSHOT_REF = 'SCREENSHOT_REF'


class EvidenceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind1
    value: Annotated[str, Field(max_length=2000, min_length=1)]


class BrowserOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: UUID
    generation: Annotated[int, Field(ge=1)]
    outcome: Outcome
    not_submitted_proven: bool
    observed_at: Utc
    job_id: Annotated[str, Field(max_length=100, min_length=1)]
    form_fingerprint: Annotated[str, Field(max_length=64)]
    evidence: Annotated[list[EvidenceItem], Field(max_length=20)]


class Operation5(Enum):
    export_preview = 'export_preview'
    export_confirm = 'export_confirm'
    delete_preview = 'delete_preview'
    delete_confirm = 'delete_confirm'
    restore_preview = 'restore_preview'
    restore_confirm = 'restore_confirm'


class PrivacyCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    operation: Operation5
    subject_ids: Annotated[list[UUID], Field(max_length=1000, min_length=1)]
    preview_id: UUID | None = None
    expected_revision: Revision | None = None
    encrypted: bool | None = None


class ParentId(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class CheckpointPut(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    run_id: UUID
    generation: Annotated[int, Field(ge=1)]
    namespace: Annotated[str, Field(max_length=200)]
    checkpoint_id: Annotated[str, Field(max_length=100, min_length=1)]
    parent_id: ParentId | None
    checkpoint_json: Annotated[str, Field(max_length=1048576)]
    metadata_json: Annotated[str, Field(max_length=65536)]
    new_versions_json: Annotated[str, Field(max_length=65536)]


class Write(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    index: int
    channel: Annotated[str, Field(max_length=100, min_length=1)]
    value_json: Annotated[str, Field(max_length=1048576)]


class CheckpointWrites(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: UUID
    run_id: UUID
    generation: Annotated[int, Field(ge=1)]
    namespace: Annotated[str, Field(max_length=200)]
    checkpoint_id: Annotated[str, Field(max_length=100, min_length=1)]
    task_id: Annotated[str, Field(max_length=100, min_length=1)]
    task_path: Annotated[str, Field(max_length=1000)]
    writes: Annotated[list[Write], Field(max_length=1000)]


class WorkKind(Enum):
    DISCOVER = 'DISCOVER'
    PREPARE = 'PREPARE'
    RECONCILE = 'RECONCILE'


class Lease(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lease_id: Id
    run_id: Id
    worker_id: Id
    generation: Annotated[int, Field(ge=1)]
    expires_at: Utc
    work_kind: WorkKind


class WorkAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: bool
    lease: Lease | None


class HeartbeatResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lease_id: Id
    generation: Annotated[int, Field(ge=1)]
    expires_at: Utc
    fenced: bool


class CheckpointConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_id: Id
    checkpoint_ns: str
    checkpoint_id: Annotated[str, Field(min_length=1)]


class CheckpointWriteResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checkpoint_id: str
    accepted_writes: Annotated[int, Field(ge=0)]
